// Code generated by "stringer -type BezierTableIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BezierTest1-0]
	_ = x[BezierTest2-1]
	_ = x[BezierTableSize-2]
}

const _BezierTableIndex_name = "BezierTest1BezierTest2BezierTableSize"

var _BezierTableIndex_index = [...]uint8{0, 11, 22, 37}

func (i BezierTableIndex) String() string {
	if i < 0 || i >= BezierTableIndex(len(_BezierTableIndex_index)-1) {
		return "BezierTableIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BezierTableIndex_name[_BezierTableIndex_index[i]:_BezierTableIndex_index[i+1]]
}
