// Code generated by "stringer -type BezierTableIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BezierBoardHideTile-0]
	_ = x[BezierBoardHideTileAlpha-1]
	_ = x[BezierBoardHideButton-2]
	_ = x[BezierBoardShowTileYoffset-3]
	_ = x[BezierBoardShowTileAlpha-4]
	_ = x[BezierBoardShowTileScale-5]
	_ = x[BezierTableSize-6]
}

const _BezierTableIndex_name = "BezierBoardHideTileBezierBoardHideTileAlphaBezierBoardHideButtonBezierBoardShowTileYoffsetBezierBoardShowTileAlphaBezierBoardShowTileScaleBezierTableSize"

var _BezierTableIndex_index = [...]uint8{0, 19, 43, 64, 90, 114, 138, 153}

func (i BezierTableIndex) String() string {
	if i < 0 || i >= BezierTableIndex(len(_BezierTableIndex_index)-1) {
		return "BezierTableIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BezierTableIndex_name[_BezierTableIndex_index[i]:_BezierTableIndex_index[i+1]]
}
