// Code generated by "stringer -type ColorTableIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorBg-0]
	_ = x[ColorTileNormal1-1]
	_ = x[ColorTileNormal2-2]
	_ = x[ColorTileNormalStroke-3]
	_ = x[ColorTileRevealed1-4]
	_ = x[ColorTileRevealed2-5]
	_ = x[ColorTileRevealedStroke-6]
	_ = x[ColorNumber-7]
	_ = x[ColorMine-8]
	_ = x[ColorFlag-9]
}

const _ColorTableIndex_name = "ColorBgColorTileNormal1ColorTileNormal2ColorTileNormalStrokeColorTileRevealed1ColorTileRevealed2ColorTileRevealedStrokeColorNumberColorMineColorFlag"

var _ColorTableIndex_index = [...]uint8{0, 7, 23, 39, 60, 78, 96, 119, 130, 139, 148}

func (i ColorTableIndex) String() string {
	if i < 0 || i >= ColorTableIndex(len(_ColorTableIndex_index)-1) {
		return "ColorTableIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorTableIndex_name[_ColorTableIndex_index[i]:_ColorTableIndex_index[i+1]]
}
