// Code generated by "stringer -type ColorTableIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorBg-0]
	_ = x[ColorTopUITitle-1]
	_ = x[ColorTopUIButton-2]
	_ = x[ColorTopUIButtonOnHover-3]
	_ = x[ColorTopUIButtonOnDown-4]
	_ = x[ColorTileNormal1-5]
	_ = x[ColorTileNormal2-6]
	_ = x[ColorTileNormalStroke-7]
	_ = x[ColorTileRevealed1-8]
	_ = x[ColorTileRevealed2-9]
	_ = x[ColorTileRevealedStroke-10]
	_ = x[ColorNumber1-11]
	_ = x[ColorNumber2-12]
	_ = x[ColorNumber3-13]
	_ = x[ColorNumber4-14]
	_ = x[ColorNumber5-15]
	_ = x[ColorNumber6-16]
	_ = x[ColorNumber7-17]
	_ = x[ColorNumber8-18]
	_ = x[ColorMine-19]
	_ = x[ColorFlag-20]
	_ = x[ColorTileHighLight-21]
	_ = x[ColorTableSize-22]
}

const _ColorTableIndex_name = "ColorBgColorTopUITitleColorTopUIButtonColorTopUIButtonOnHoverColorTopUIButtonOnDownColorTileNormal1ColorTileNormal2ColorTileNormalStrokeColorTileRevealed1ColorTileRevealed2ColorTileRevealedStrokeColorNumber1ColorNumber2ColorNumber3ColorNumber4ColorNumber5ColorNumber6ColorNumber7ColorNumber8ColorMineColorFlagColorTileHighLightColorTableSize"

var _ColorTableIndex_index = [...]uint16{0, 7, 22, 38, 61, 83, 99, 115, 136, 154, 172, 195, 207, 219, 231, 243, 255, 267, 279, 291, 300, 309, 327, 341}

func (i ColorTableIndex) String() string {
	if i < 0 || i >= ColorTableIndex(len(_ColorTableIndex_index)-1) {
		return "ColorTableIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorTableIndex_name[_ColorTableIndex_index[i]:_ColorTableIndex_index[i+1]]
}
