// do not edit!
// generated by sound_srcs_gen.go

package main

const (
	SeSwitch1      = "tmps/converted/UI_SFX_Set/switch1.ogg"
	SeSwitch2      = "tmps/converted/UI_SFX_Set/switch2.ogg"
	SeSwitch3      = "tmps/converted/UI_SFX_Set/switch3.ogg"
	SeSwitch4      = "tmps/converted/UI_SFX_Set/switch4.ogg"
	SeSwitch5      = "tmps/converted/UI_SFX_Set/switch5.ogg"
	SeMenu4        = "tmps/converted/GUI_Sound_Effects_by_Lokif/misc_menu_4.ogg"
	SeSave         = "tmps/converted/GUI_Sound_Effects_by_Lokif/save.ogg"
	SeMiscSounc    = "tmps/converted/GUI_Sound_Effects_by_Lokif/misc_sound.ogg"
	SeNegative2    = "tmps/converted/GUI_Sound_Effects_by_Lokif/negative_2.ogg"
	SePositive     = "tmps/converted/GUI_Sound_Effects_by_Lokif/positive.ogg"
	SeClick1       = "tmps/converted/UI_SFX_Set/click1.ogg"
	SeDustbin      = "tmps/converted/interface/dustbin.ogg"
	SeSwitch38     = "tmps/converted/UI_SFX_Set/switch38.ogg"
	SeUnlinkSummer = "tmps/converted/krank_sounds/summer/unlink.ogg"
	SeCut          = "tmps/converted/interface/cut.ogg"
	SeLinkSummer   = "tmps/converted/krank_sounds/summer/link.ogg"
	SeWobble       = "tmps/converted/wobble.wav"
	SeWobble2      = "tmps/converted/wobble2.wav"
	SeWobble3      = "tmps/converted/wobble3.wav"
	SeNoteC        = "tmps/converted/note_sounds/note-sounds-c.wav"
	SeNoteD        = "tmps/converted/note_sounds/note-sounds-d.wav"
	SeNoteE        = "tmps/converted/note_sounds/note-sounds-e.wav"
	SeNoteF        = "tmps/converted/note_sounds/note-sounds-f.wav"
	SeNoteG        = "tmps/converted/note_sounds/note-sounds-g.wav"
	SeNoteA        = "tmps/converted/note_sounds/note-sounds-a.wav"
	SeNoteB        = "tmps/converted/note_sounds/note-sounds-b.wav"
	SeNoteC2       = "tmps/converted/note_sounds/note-sounds-c-2.wav"
	SeBigHit       = "tmps/converted/note_sounds/big-hit.wav"
	SeBigHit2      = "tmps/converted/note_sounds/big-hit2.wav"
	SeBigHit3      = "tmps/converted/note_sounds/big-hit3.wav"
	SeTile         = "tmps/converted/tile-sound.wav"
	SeTile2        = "tmps/converted/tile-sound2.wav"
	SeDomino       = "tmps/converted/domino.wav"
	SeDomino2      = "tmps/converted/domino2.wav"
	SeDomino3      = "tmps/converted/domino3.wav"
	SeDomino4      = "tmps/converted/domino4.wav"
	SeDomino5      = "tmps/converted/domino5.wav"
	SeDomino6      = "tmps/converted/domino6.wav"
	SePop1         = "tmps/converted/pop/244652__greenvwbeetle__pop-4.ogg"
	SePop2         = "tmps/converted/pop/260614__kwahmah_02__pop.ogg"
	SePop3         = "tmps/converted/pop/463393__vilkas_sound__vs-pop_7.ogg"
	SeNewCut       = "tmps/converted/new-cut.wav"
	SeNewCut2      = "tmps/converted/new-cut2.wav"
)

var SoundSrcs = []string{
	"tmps/converted/UI_SFX_Set/switch1.ogg",
	"tmps/converted/UI_SFX_Set/switch2.ogg",
	"tmps/converted/UI_SFX_Set/switch3.ogg",
	"tmps/converted/UI_SFX_Set/switch4.ogg",
	"tmps/converted/UI_SFX_Set/switch5.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/misc_menu_4.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/save.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/misc_sound.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/negative_2.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/positive.ogg",
	"tmps/converted/UI_SFX_Set/click1.ogg",
	"tmps/converted/interface/dustbin.ogg",
	"tmps/converted/UI_SFX_Set/switch38.ogg",
	"tmps/converted/krank_sounds/summer/unlink.ogg",
	"tmps/converted/interface/cut.ogg",
	"tmps/converted/krank_sounds/summer/link.ogg",
	"tmps/converted/wobble.wav",
	"tmps/converted/wobble2.wav",
	"tmps/converted/wobble3.wav",
	"tmps/converted/note_sounds/note-sounds-c.wav",
	"tmps/converted/note_sounds/note-sounds-d.wav",
	"tmps/converted/note_sounds/note-sounds-e.wav",
	"tmps/converted/note_sounds/note-sounds-f.wav",
	"tmps/converted/note_sounds/note-sounds-g.wav",
	"tmps/converted/note_sounds/note-sounds-a.wav",
	"tmps/converted/note_sounds/note-sounds-b.wav",
	"tmps/converted/note_sounds/note-sounds-c-2.wav",
	"tmps/converted/note_sounds/big-hit.wav",
	"tmps/converted/note_sounds/big-hit2.wav",
	"tmps/converted/note_sounds/big-hit3.wav",
	"tmps/converted/tile-sound.wav",
	"tmps/converted/tile-sound2.wav",
	"tmps/converted/domino.wav",
	"tmps/converted/domino2.wav",
	"tmps/converted/domino3.wav",
	"tmps/converted/domino4.wav",
	"tmps/converted/domino5.wav",
	"tmps/converted/domino6.wav",
	"tmps/converted/pop/244652__greenvwbeetle__pop-4.ogg",
	"tmps/converted/pop/260614__kwahmah_02__pop.ogg",
	"tmps/converted/pop/463393__vilkas_sound__vs-pop_7.ogg",
	"tmps/converted/new-cut.wav",
	"tmps/converted/new-cut2.wav",
}
