// do not edit!
// generated by sound_srcs_gen.go

package main

const (
	SeSwitch1      = "tmps/converted/UI_SFX_Set/switch1.ogg"
	SeSwitch2      = "tmps/converted/UI_SFX_Set/switch2.ogg"
	SeSwitch3      = "tmps/converted/UI_SFX_Set/switch3.ogg"
	SeSwitch4      = "tmps/converted/UI_SFX_Set/switch4.ogg"
	SeSwitch5      = "tmps/converted/UI_SFX_Set/switch5.ogg"
	SeMenu4        = "tmps/converted/GUI_Sound_Effects_by_Lokif/misc_menu_4.ogg"
	SeSave         = "tmps/converted/GUI_Sound_Effects_by_Lokif/save.ogg"
	SeMiscSounc    = "tmps/converted/GUI_Sound_Effects_by_Lokif/misc_sound.ogg"
	SeNegative2    = "tmps/converted/GUI_Sound_Effects_by_Lokif/negative_2.ogg"
	SePositive     = "tmps/converted/GUI_Sound_Effects_by_Lokif/positive.ogg"
	SeClick1       = "tmps/converted/UI_SFX_Set/click1.ogg"
	SeDustbin      = "tmps/converted/interface/dustbin.ogg"
	SeSwitch38     = "tmps/converted/UI_SFX_Set/switch38.ogg"
	SeUnlinkSummer = "tmps/converted/krank_sounds/summer/unlink.ogg"
	SeCut          = "tmps/converted/interface/cut.ogg"
	SeLinkSummer   = "tmps/converted/krank_sounds/summer/link.ogg"
	SeWobble       = "tmps/converted/wobble.wav"
	SeWobble2      = "tmps/converted/wobble2.wav"
	SeWobble3      = "tmps/converted/wobble3.wav"
)

var SoundSrcs = []string{
	"tmps/converted/UI_SFX_Set/switch1.ogg",
	"tmps/converted/UI_SFX_Set/switch2.ogg",
	"tmps/converted/UI_SFX_Set/switch3.ogg",
	"tmps/converted/UI_SFX_Set/switch4.ogg",
	"tmps/converted/UI_SFX_Set/switch5.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/misc_menu_4.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/save.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/misc_sound.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/negative_2.ogg",
	"tmps/converted/GUI_Sound_Effects_by_Lokif/positive.ogg",
	"tmps/converted/UI_SFX_Set/click1.ogg",
	"tmps/converted/interface/dustbin.ogg",
	"tmps/converted/UI_SFX_Set/switch38.ogg",
	"tmps/converted/krank_sounds/summer/unlink.ogg",
	"tmps/converted/interface/cut.ogg",
	"tmps/converted/krank_sounds/summer/link.ogg",
	"tmps/converted/wobble.wav",
	"tmps/converted/wobble2.wav",
	"tmps/converted/wobble3.wav",
}
